steps:
# 1. Building a Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/celestine-484708/celestine-images/celestine-backend:latest'
    - '.'
  id: 'Build'

# 2. Submit an image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/celestine-484708/celestine-images/celestine-backend:latest'
  id: 'Push'

# 3. Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'celestine-backend'
    - '--image=us-central1-docker.pkg.dev/celestine-484708/celestine-images/celestine-backend:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8000'
  id: 'Deploy'

images:
- 'us-central1-docker.pkg.dev/celestine-484708/celestine-images/celestine-backend:latest'

timeout: '1200s'
